{% set name = "icdiff" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35d24b728e48b7e0a12bdb69386d3bfc7eef4fe922d0ac1cd70d6e5c11630bae

build:
  noarch: python
  number: 0
  entry_points:
    - icdiff=icdiff:start
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  commands:
    - icdiff --help

  imports:
    - icdiff

about:
  home: http://www.jefftk.com/icdiff
  license: Python-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: improved colored diff

extra:
  recipe-maintainers:
    - nicoddemus
