travis:
  secure:
    BINSTAR_TOKEN: oDsB+BrI80Sz+JyrmtxH0XoZSGOos6qJD6X2o1vngSuhbyz+MGy3I0w/vj53FgtczFJEDt47/6MJGG+XlfzpcY1qa9CLncaDuhzxErWNsrbG4zL/pbcQhrQSauMp4Cg8nJhOhxu1P5HTiHMhrzpyqDfyDEf56QHyZQTJLHxvKQQqHh+9an4MZgB3sXx8yRR0vQIVnUGSnrdx2GV3A5AUY9qPnyRaSIqlFaRsdwH8vyT+YglCCvGnquXvvj7p/qMxM2NPERZc23/O0p02o2Lsp0knXcYofSpMyQ+0Xhsn0mHi/UtjDtcyCE5tyAVX2cwWkSAbzW2SD6QHC/RNQsQ7wMQTiXnnzGwW/6nAQBkUwEe5CwcmF4I5YKKGmnQNT1IdK9yVzbbLW9YduwJSeLL3uiiEmaJGWp1iy+uxgu9P9rz1DAu22usk4WNRJG6K5Jfl/LgmTVL23zie7mYbrlIo/kkbOAHURTRbZCXplF+8J577OU9iv0umAzTdCFyHWqJLaVeozlcb7nKGtwU3d1oXPPSrZhGFW0kiX7b93Pz/W65OnRfEoa6RBq7G9zcsQXz98VbqgAyGGXg2QygvqC7jpxy7XLzgtdnxSWhS+Jy1nzGQoO0CgolSEKVxtVdpM5XOqMWEhAZKZ5zKVksmjqIy3Rs4/PRzad/d29ui5kztDBM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
